### ISSUE TITLE
how to stop a timer

### ISSUE THREAD

**Issue by Devin0203** [foex-open-source/fos-timing-actions#2]
Hi I am look for a way to stop the currently running timer when a certain column in a table becomes not null the timer has to run infinitely until that column has a value is there anyway of doing that

**Comment by puchtec** [comment]
There is the "Remove Timer Action, but for me it does not work. The only way of getting rid of the timer would be a submit.

**Comment by mnolan866** [comment]
Thanks for pointing this out, it is fixed in the next release of FOS for APEX 21.1 due out soon.

As a workaround you can edit line 52 of the script.js javascript file within the plugin and change

`FOS.timing.removeTimer();`

to

`FOS.timing.removeTimer(config.timerName);`

**Comment by Devin0203** [comment]
Yeah, I noticed that so I just ended up submitting

 

Kind Regards,

**Comment by puchtec** [comment]
> 
> 
> Thanks for pointing this out, it is fixed in the next release of FOS for APEX 21.1 due out soon.
> 
> As a workaround you can edit line 52 of the script.js javascript file within the plugin and change
> 
> `FOS.timing.removeTimer();`
> 
> to
> 
> `FOS.timing.removeTimer(config.timerName);`

Thanks @mnolan866 , this solved the issue. I have fixed it for now in my workspace. Thank you so much for the quick and excellent support.

**Comment by foex-open-source** [comment]
Fixed in just published v21.1.0
